### ISSUE TITLE
Join the `dhall-lang` umbrella project

### ISSUE THREAD

**Issue by EggBaconAndSpam** [dhall-lang/vscode-dhall-lsp-server#11]
@Gabriel439 suggested that it might be a good idea to have `vscode-dhall-lsp-server` and `dhall-lsp-server` under the same roof since they are meant to be used in tandem in any case.

Also, since the VSCode integration is now in a very useable state, it may be time to go official as it were. What are your thought on this, @PanAeon?

**Comment by PanAeon** [comment]
I'm totally for it! Just a few things:

- we might want to transfer Dhall Language Support (syntax highlighting) plugin as well
- "vscode-dhall-lsp-server" name feels a bit boring for me. Maybe we can change it to something shorter. The display name in the marketplace is "Dhall LSP Server".
- When I published it I was young and stupid and published it using my own publisher. I think I'll create a new publisher, the only thing is that I'll have to re-publish the extensions which will drop stats for them and users will have to reinstall them. It looks like a publisher can be owned by multiple member, so then I'll add you to its members.

**Comment by EggBaconAndSpam** [comment]
>     * we might want to transfer Dhall Language Support (syntax highlighting) plugin as well
Good idea!
>     * "vscode-dhall-lsp-server" name feels a bit boring for me. Maybe we can change it to something shorter. The display name in the marketplace is "Dhall LSP Server".
I second that.
>     * When I published it I was young and stupid and published it using my own publisher. I think I'll create a new publisher, the only thing is that I'll have to re-publish the extensions which will drop stats for them and users will have to reinstall them. It looks like a publisher can be owned by multiple member, so then I'll add you to its members.
To be honest I've got no idea what the process to publish a VSCode extension looks like... Regarding resetting of statistics etc. I think we can do that once, especially now where the extension isn't all that popular yet.

**Comment by sjakobi** [comment]
> "vscode-dhall-lsp-server" name feels a bit boring for me. Maybe we can change it to something shorter. The display name in the marketplace is "Dhall LSP Server".

The name might be boring, but it expresses very clearly what the project is about and it's pretty searchable. It could be worse! ;)

**Comment by EggBaconAndSpam** [comment]
On second thought, shouldn't the VSCode plugin be called "Dhall LSP client"?

**Comment by Gabriel439** [comment]
My advice is to use the same naming convention that other language plugins use (whatever that is, I haven't checked yet)

**Comment by EggBaconAndSpam** [comment]
I think its time to get things moving. From what I see the following is to be done:

1. Transfer ownership of the repo to the *dhall-lang* organisation (according to [this document](https://help.github.com/en/github/administering-a-repository/transferring-a-repository#repository-transfers-and-organizations) this seems to require some kind of permissions inside the organisation?)
2. Document/script the release process (i.e. publishing the extension to the vscode marketplace)
3. **(optional)** Add another user (potentially controlled by @Gabriel439) with publishing rights to @PanAeon's marketplace account.

Step 1 being the most urgent of course. @PanAeon could you try transferring ownership and inform us if github complains about permissions?

Regarding steps 2 and 3, I think 2 would take work off @PanAeon's shoulders (and also be useful long term), while we can postpone 3 for the time being. We can talk about re-publishing the extension under a different 'publisher' later.

**Comment by PanAeon** [comment]
@EggBaconAndSpam 

1. Hi, I can't transfer the repository to the `dhall-lang` project because I don't have permissions to create a public repo there. So Gabriel needs to either give me a temporary permissions or just to push the code to a new repo. We've got like 4 issues open right now I think it's not a problem to manually recreate them.
2. In pinciple, the process is documented in details [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension), but I think I'll still create `Publishing.md` or something where I'll put the exact steps. 
3. I think this step is quite important, in case I'm unavailable we need other people to have ways to update the extension on the marketplace. @EggBaconAndSpam  If you OK with creating an azure account and personal access token as in [publishing extensions guide](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) then I'll add you to a new publisher, we'll check that everything is fine and then I'll move the extension to it. What do you think?

**Comment by Gabriel439** [comment]
@PanAeon: Try now.  I think I gave you permission to transfer a repository to `dhall-lang`

**Comment by PanAeon** [comment]
@Gabriel439 Hi, Github still says "You don’t have the permission to create public repositories on dhall-lang". Btw I'll also transfer syntax highlighting plugin as  well.

**Comment by Gabriel439** [comment]
@PanAeon: You may need to accept the invite first before you have permission

**Comment by PanAeon** [comment]
@Gabriel439 Still the same. Maybe I've got the default read permissions?

**Comment by Gabriel439** [comment]
@PanAeon: Whoops, my mistake.  I sent a new invite

**Comment by Gabriel439** [comment]
The transfer appears to be successful! 🎉

**Comment by EggBaconAndSpam** [comment]
Yay!
