### ISSUE TITLE
Difference between this repo and the PanAeon fork?

### ISSUE THREAD

**Issue by samuela** [dhall-lang/vscode-dhall-lsp-server#32]
I noticed that the official VSCode [extension](https://marketplace.visualstudio.com/items?itemName=dhall.vscode-dhall-lsp-server) (as linked to from the home page) lists PanAeon/vscode-dhall-lsp-server as its source. That seems odd though considering that it's a fork of the (presumably official) dhall-lang/vscode-dhall-lsp-server.

What's the difference between these two repos? Which one is the official source?

**Comment by PanAeon** [comment]
This is the official repo. I'll update README.md and other references in the project accordingly.

**Comment by PanAeon** [comment]
#33
